//
// Created by ntoylker on 27/12/2023.
//

#ifndef STM32H7A3ZIQSETUP_PSUENABLEMONITORTASK_HPP
#define STM32H7A3ZIQSETUP_PSUENABLEMONITORTASK_HPP

#endif //STM32H7A3ZIQSETUP_PSUENABLEMONITORTASK_HPP
